### PR TITLE
Bubble synthetic event so more websites can catch them

### PR DESCRIPTION
**Pull request by luisherranz**
There are some client-side JavaScript frameworks like React or Ember that without the `bubbles: true` option in the input event don't trigger its own `onChange` events when the input changes.

Two examples are of websites that don't work without this option are the email editor of [frontapp.com](https://frontapp.com/) and the post editor of all the [Discourse](https://www.discourse.org/) forums. I'm sure there will be many more 🙂

### CODE REVIEW

**Comment by fregante** [comment]
Good point, I think this applies to every event. Could you add `{bubbles: true}` to all of them?

**Comment by luisherranz** [comment]
What events, `KeyboardEvent` and `CompositionEvent`?

https://github.com/GhostText/GhostText/blob/6cb9670f813e387edb7452767350bfa56d75245c/source/ghost-text.js#L163-L172

**Comment by fregante** [comment]
All of them

**Comment by fregante** [comment]
Note to self: Wait for Firefox to accept the current version before merging this and releasing  a new version.

**Comment by luisherranz** [comment]
I don't think that [`KeyboardEvent`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent) and [`CompositionEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent/CompositionEvent) can bubble.

**Comment by fregante** [comment]
> The KeyboardEventInit dictionary also accepts fields from the UIEventInit and EventInit dictionaries.

**Comment by luisherranz** [comment]
Done 👍

**Comment by fregante** [comment]
Thank you Luis!

**Comment by luisherranz** [comment]
No problem! 🙂👍

**Pull request merged**
