### PR TITLE
Allow activating GhostText by right clicking on fields

### LINKED ISSUE #131: Start editing via context menu
# Setup

Browser: Firefox
Editor: N/A

# Description

It would be nice to be able to start editing a text area by right-clicking and selecting an appropriate option from the context menu. I'm used to doing this with It's All Text.

This could also save having to deal with the "there are multiple text areas" popup, since it should know which text area the context menu is for.

### PR DESCRIPTION
**Pull request by mavit**
Fixes #131.

### CODE REVIEW

**Comment by fregante** [comment]
Thank you! Does this work on code mirror fields too?

**Comment by mavit** [comment]
I hadn't heard of that before, but I've just tried it at https://codemirror.net/ and it seems fine.

**Comment by fregante** [comment]
Indeed it works, pretty cool! Goes to show how a little contribution goes a long way, instead of waiting 3 years 😁

**Comment by fregante** [comment]
Thanks @mavit!

**Pull request merged**
